baseURL: https://chapter-07-18.hugoinaction.com
languageCode: en-us
title: Acme Corporation
theme: https://github.com/CoveTar/Eclectic
enableEmoji: true
enableGitInfo: true
pagination:
  pagerSize: 10
